general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
}

# Blocco schermo (3 minuti = 180 secondi)
listener {
    timeout = 180
    on-timeout = loginctl lock-session
}

# Spegnimento monitor (3.5 minuti = 210 secondi)
listener {
    timeout = 210
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# Sospensione PC (10 minuti = 600 secondi)
listener {
    timeout = 600
    on-timeout = systemctl suspend
}
